name: build playgrounds
on:
  release:
    types: [published]
  push:
    tags:
      # https://www.digitalocean.com/community/tools/glob?comments=true&glob=%3F%28v%29%2B%28%5B0-9%5D%29.%2B%28%5B0-9%5D%29%3F%28.%2B%28%5B0-9%5D%29%29&matches=false&tests=_1.0&tests=_v1.0&tests=artifact_v1&tests=artifact_v1.0&tests=artifact_v1.0.1&tests=artifact_v11.22&tests=artifact_v1.0.1.9&tests=aqua-menu-bar_1.2&tests=aqua-menu-bar_1.1.2&tests=aqua-menu-bar_1.1.23&tests=artifact_v11.22_b9&tests=artifact_v11.22_build_9&tests=1.2&tests=1.12&tests=12.1&tests=12.12&tests=1.1.1&tests=1.1.12&tests=1.12.1&tests=12.1.1&tests=1.12.12&tests=12.1.12&tests=12.12.1&tests=12.12.12&tests=1.1.1.1&tests=1.1.1.12&tests=v1.2&tests=v1.12&tests=v12.1&tests=v12.12&tests=v1.1.1&tests=v1.1.12&tests=v1.12.1&tests=v12.1.1&tests=v1.12.12&tests=v12.1.12&tests=v12.12.1&tests=v12.12.12&tests=v1.1.1.1&tests=v1.1.1.12
      # 1.2, 1.1.1, 1.1.12
      # v1.2, v1.1.1, v1.1.12
      - '?(v)+([0-9]).+([0-9])?(.+([0-9]))'
  workflow_dispatch: # manual trigger

env:
  TERM: xterm-256color
  DEVELOPER_DIR: /Applications/Xcode_${{ vars.XCODE_VERSION }}.app/Contents/Developer

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        platform: [macOS, iOS]
    timeout-minutes: 30
    runs-on: ${{ vars.MACOS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Download visionOS simulator
        if: matrix.platform == 'visionOS'
        run: xcodebuild -downloadPlatform visionOS
      - name: Build ChouTiPlayground-${{ matrix.platform }}
        if: success() || failure()
        run: make build-playground-${{ matrix.platform }}
