name: build
on:
  push:
    branches-ignore:
      - "github-actions/**" # ignore github-actions branches
      - "dependabot/**" # ignore dependabot branches
  pull_request: # any pull request against any branch
  workflow_dispatch: # manual trigger to run workflow
  schedule:
    # ┌───────────── minute (0 - 59)
    # │ ┌───────────── hour (0 - 23)
    # │ │ ┌───────────── day of the month (1 - 31)
    # │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    # │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    # │ │ │ │ │
    # * * * * *
    - cron: "30 1,15 * * *" # every day at 1:30 UTC (17:30 PST, 18:30 PDT) and 15:30 UTC (7:30 PST, 8:30 PDT)

env:
  TERM: xterm-256color
  DEVELOPER_DIR: /Applications/Xcode_${{ vars.XCODE_VERSION }}.app/Contents/Developer

jobs:
  build:
    name: Build
    runs-on: ${{ vars.MACOS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Build for release
        run: make build-release

  test:
    name: Test
    strategy:
      fail-fast: false
      matrix:
        platform: [iOS, visionOS]
    timeout-minutes: 30
    runs-on: ${{ vars.MACOS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Download visionOS simulator
        if: matrix.platform == 'visionOS'
        run: xcodebuild -downloadPlatform visionOS
      - name: Test
        if: success() || failure()
        run: make test-${{ matrix.platform }}

  test-codecov:
    name: Test (macOS)
    runs-on: ${{ vars.MACOS }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Bootstrap
        uses: ./.github/actions/bootstrap
      - name: Test with Codecov
        if: success() || failure()
        run: make test-codecov
      - name: Upload code coverage
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: .build/debug/codecov/coverage.lcov
          disable_search: true
          flags: ChouTiUI
          name: ChouTiUI
          fail_ci_if_error: true
